# Kubernetes Prometheus Alerting Rules
# Defines alert conditions for Kubernetes cluster monitoring

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
  labels:
    app: prometheus
data:
  kubernetes.rules.yml: |
    groups:
    - name: kubernetes-apps
      rules:
      - alert: KubePodCrashLooping
        expr: max_over_time(kube_pod_container_status_restarts_total[15m]) - min_over_time(kube_pod_container_status_restarts_total[15m]) > 5
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is crash looping
          description: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) has restarted {{ $value }} times in the last 15 minutes.

      - alert: KubePodNotReady
        expr: kube_pod_status_ready{condition="false"} == 1
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: Pod {{ $labels.namespace }}/{{ $labels.pod }} not ready
          description: Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for longer than 15 minutes.

      - alert: KubeDeploymentGenerationMismatch
        expr: kube_deployment_status_generation != kube_deployment_metadata_generation
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: Deployment generation mismatch due to possible roll-back
          description: Deployment generation for {{ $labels.namespace }}/{{ $labels.deployment }} does not match.

      - alert: KubeDeploymentReplicasMismatch
        expr: (kube_deployment_spec_replicas != kube_deployment_status_replicas_available) and (changes(kube_deployment_status_replicas_updated[10m]) == 0)
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has not matched the expected number of replicas
          description: Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has not matched the expected number of replicas for longer than 15 minutes.

      - alert: KubeStatefulSetReplicasMismatch
        expr: (kube_statefulset_status_replicas_ready != kube_statefulset_status_replicas) and (changes(kube_statefulset_status_replicas_updated[10m]) == 0)
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }} has not matched the expected number of replicas
          description: StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }} has not matched the expected number of replicas for longer than 15 minutes.

      - alert: KubeHpaReplicasMismatch
        expr: (kube_horizontalpodautoscaler_status_desired_replicas != kube_horizontalpodautoscaler_status_current_replicas) and (kube_horizontalpodautoscaler_status_current_replicas > kube_horizontalpodautoscaler_spec_min_replicas) and (kube_horizontalpodautoscaler_status_current_replicas < kube_horizontalpodautoscaler_spec_max_replicas) and changes(kube_horizontalpodautoscaler_status_current_replicas[15m]) == 0
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: HPA {{ $labels.namespace }}/{{ $labels.horizontalpodautoscaler }} has not matched desired number of replicas
          description: HPA {{ $labels.namespace }}/{{ $labels.horizontalpodautoscaler }} has not matched the desired number of replicas for longer than 15 minutes.

    - name: kubernetes-resources
      rules:
      - alert: KubeCPUOvercommit
        expr: sum(namespace:kube_pod_container_resource_requests_cpu_cores:sum{}) by (cluster) / sum(kube_node_status_allocatable_cpu_cores) by (cluster) > 1.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Cluster has overcommitted CPU resource requests
          description: Cluster has overcommitted CPU resource requests for Pods by {{ $value }} CPU cores and cannot tolerate node failure.

      - alert: KubeMemoryOvercommit
        expr: sum(namespace:kube_pod_container_resource_requests_memory_bytes:sum{}) by (cluster) / sum(kube_node_status_allocatable_memory_bytes) by (cluster) > 1.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Cluster has overcommitted memory resource requests
          description: Cluster has overcommitted memory resource requests for Pods by {{ $value | humanize }} bytes and cannot tolerate node failure.

      - alert: KubeCPUQuotaOvercommit
        expr: sum(kube_resourcequota{job="kube-state-metrics", type="hard", resource="cpu"}) by (cluster) / sum(kube_node_status_allocatable_cpu_cores) by (cluster) > 1.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Cluster has overcommitted CPU resource quotas
          description: Cluster has overcommitted CPU resource quotas.

      - alert: KubeMemoryQuotaOvercommit
        expr: sum(kube_resourcequota{job="kube-state-metrics", type="hard", resource="memory"}) by (cluster) / sum(kube_node_status_allocatable_memory_bytes{job="kube-state-metrics"}) by (cluster) > 1.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Cluster has overcommitted memory resource quotas
          description: Cluster has overcommitted memory resource quotas.

    - name: kubernetes-storage
      rules:
      - alert: KubePersistentVolumeFillingUp
        expr: (kubelet_volume_stats_available_bytes{job="kubelet"} / kubelet_volume_stats_capacity_bytes{job="kubelet"}) < 0.03 and kubelet_volume_stats_used_bytes{job="kubelet"} > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: PersistentVolume is filling up
          description: The PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is only {{ $value | humanizePercentage }} free.

      - alert: KubePersistentVolumeFillingUp
        expr: (kubelet_volume_stats_available_bytes{job="kubelet"} / kubelet_volume_stats_capacity_bytes{job="kubelet"}) < 0.15 and kubelet_volume_stats_used_bytes{job="kubelet"} > 0 and predict_linear(kubelet_volume_stats_available_bytes{job="kubelet"}[6h], 4 * 24 * 3600) < 0
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: PersistentVolume is filling up
          description: Based on recent sampling, the PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is expected to fill up within four days. Currently {{ $value | humanizePercentage }} is available.

  node.rules.yml: |
    groups:
    - name: kubernetes-system
      rules:
      - alert: KubeNodeNotReady
        expr: kube_node_status_condition{job="kube-state-metrics",condition="Ready",status="true"} == 0
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: Node {{ $labels.node }} is not ready
          description: Node {{ $labels.node }} has been unready for more than 15 minutes.

      - alert: KubeNodeUnreachable
        expr: (kube_node_spec_taint{job="kube-state-metrics",key="node.kubernetes.io/unreachable",effect="NoSchedule"} unless ignoring(key,value) kube_node_spec_taint{job="kube-state-metrics",key=~"ToBeDeletedByClusterAutoscaler|cloud.google.com/impending-node-termination|aws-node-termination-handler/spot-itn"}) == 1
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: Node {{ $labels.node }} is unreachable
          description: Node {{ $labels.node }} is unreachable and some workloads may be rescheduled.

      - alert: KubeletTooManyPods
        expr: count by(cluster, node) ((kube_pod_status_phase{job="kube-state-metrics",phase="Running"} == 1) * on(instance,pod,namespace,cluster) group_left(node) topk by(instance,pod,namespace,cluster) (1, kube_pod_info{job="kube-state-metrics"})) / max by(cluster, node) (kube_node_status_capacity_pods{job="kube-state-metrics"} != 1) > 0.95
        for: 15m
        labels:
          severity: info
        annotations:
          summary: Kubelet is running at capacity
          description: Kubelet {{ $labels.node }} is running at {{ $value | humanizePercentage }} of its Pod capacity.

      - alert: KubeNodeReadinessFlapping
        expr: sum(changes(kube_node_status_condition{status="true",condition="Ready"}[15m])) by (cluster, node) > 2
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: Node readiness status is flapping
          description: The readiness status of node {{ $labels.node }} has changed {{ $value }} times in the last 15 minutes.