services:
  neo4j:
    image: neo4j:5.15
    restart: unless-stopped
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH:-neo4j/neo4j123}
      NEO4J_PLUGINS: ${NEO4J_PLUGINS:-["graph-data-science"]}
      NEO4J_dbms_security_procedures_unrestricted: gds.*
      NEO4J_dbms_security_procedures_allowlist: gds.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.neo4j.rule=Host(`neo4j.localhost`)"
      - "traefik.http.routers.neo4j.entrypoints=web"
      - "traefik.http.services.neo4j.loadbalancer.server.port=7474"
    networks:
      - shared-networks
    healthcheck:
      test: [ "CMD", "cypher-shell", "-u", "neo4j", "-p", "neo4j123", "RETURN 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:


networks:
  shared-networks:
    external: true
