# Prometheus Alerting Rules
# Defines alert conditions for infrastructure and application monitoring

groups:
- name: infrastructure.rules
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

  - alert: HighCPUUsage
    expr: 100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is above 80% for more than 10 minutes."

  - alert: HighMemoryUsage
    expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage detected"
      description: "Memory usage is above 85% for more than 10 minutes."

  - alert: DiskSpaceLow
    expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 10
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Disk space critically low"
      description: "Disk space on root filesystem is below 10%."

  - alert: DiskSpaceWarning
    expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 20
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Disk space low"
      description: "Disk space on root filesystem is below 20%."

- name: docker.rules
  rules:
  - alert: ContainerDown
    expr: absent(container_last_seen{name!=""})
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Container {{ $labels.name }} is down"
      description: "Container {{ $labels.name }} has been down for more than 5 minutes."

  - alert: ContainerHighCPU
    expr: rate(container_cpu_usage_seconds_total{name!=""}[5m]) * 100 > 80
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Container {{ $labels.name }} high CPU usage"
      description: "Container {{ $labels.name }} CPU usage is above 80% for more than 10 minutes."

  - alert: ContainerHighMemory
    expr: (container_memory_usage_bytes{name!=""} / container_spec_memory_limit_bytes) * 100 > 85
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Container {{ $labels.name }} high memory usage"
      description: "Container {{ $labels.name }} memory usage is above 85% for more than 10 minutes."

  - alert: ContainerRestarting
    expr: increase(container_restart_count{name!=""}[1h]) > 5
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: "Container {{ $labels.name }} restarting frequently"
      description: "Container {{ $labels.name }} has restarted more than 5 times in the last hour."

- name: application.rules
  rules:
  - alert: HighErrorRate
    expr: (rate(http_requests_total{status=~"4..|5.."}[5m]) / rate(http_requests_total[5m])) * 100 > 5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High error rate detected"
      description: "Error rate is above 5% for more than 5 minutes."

  - alert: HighResponseTime
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High response time detected"
      description: "95th percentile response time is above 2 seconds for more than 10 minutes."

  - alert: DatabaseConnectionsHigh
    expr: postgres_connections_active > postgres_connections_max * 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Database connections high"
      description: "Database connections are above 80% of maximum for more than 5 minutes."

  - alert: ServiceUnavailable
    expr: up{job=~".*-service"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Service {{ $labels.job }} unavailable"
      description: "Service {{ $labels.job }} has been unavailable for more than 1 minute."

- name: security.rules
  rules:
  - alert: SuspiciousLoginAttempts
    expr: rate(auth_failures_total[5m]) > 10
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Suspicious login attempts detected"
      description: "More than 10 failed login attempts per minute detected."

  - alert: SecurityViolation
    expr: increase(container_security_violations_total[5m]) > 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: "Container security violation detected"
      description: "Container security violation detected: {{ $labels.violation_type }}"

  - alert: SSLCertificateExpiringSoon
    expr: (ssl_certificate_expiry_seconds - time()) / 86400 < 7
    for: 1h
    labels:
      severity: warning
    annotations:
      summary: "SSL certificate expiring soon"
      description: "SSL certificate for {{ $labels.domain }} expires in {{ $value }} days."

  - alert: SSLCertificateExpired
    expr: (ssl_certificate_expiry_seconds - time()) < 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: "SSL certificate expired"
      description: "SSL certificate for {{ $labels.domain }} has expired."

- name: monitoring.rules
  rules:
  - alert: PrometheusDown
    expr: up{job="prometheus"} == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Prometheus server down"
      description: "Prometheus server has been down for more than 5 minutes."

  - alert: GrafanaDown
    expr: up{job="grafana"} == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Grafana server down"
      description: "Grafana server has been down for more than 5 minutes."

  - alert: ElasticsearchDown
    expr: up{job="elasticsearch"} == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Elasticsearch server down"
      description: "Elasticsearch server has been down for more than 5 minutes."

  - alert: PrometheusConfigReloadFailed
    expr: prometheus_config_last_reload_successful == 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Prometheus config reload failed"
      description: "Prometheus configuration reload has failed."

  - alert: AlertmanagerDown
    expr: up{job="alertmanager"} == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Alertmanager down"
      description: "Alertmanager has been down for more than 5 minutes."