services:
  jenkins:
    container_name: jenkins-container
    image: jenkins/jenkins:lts
    restart: unless-stopped
    user: root
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true
    ports:
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.localhost`)"
      - "traefik.http.routers.jenkins.entrypoints=web"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    networks:
      - shared-networks
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/login" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  jenkins_home:


networks:
  shared-networks:
    external: true
