services:
  mongodb:
    container_name: mongodb-container
    image: mongo:7
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=admin

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

    networks:
      - shared-networks

    healthcheck:

      test: [ "CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy:

      resources:

        limits:

          memory: 1G
        reservations:

          memory: 512M

volumes:
  mongodb_data:
  mongodb_config:


networks:
  shared-networks:
    external: true
