services:
  wordpress:
    container_name: wordpress-container
    image: wordpress:latest
    # Remove direct port mapping - access through Traefik
    # ports:
    #   - 89:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.localhost`)"
      - "traefik.http.routers.wordpress.entrypoints=web"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - shared-networks
      - wordpress-internal
    depends_on:
      - db

volumes:
  db_data:


networks:
  shared-networks:
    external: true
  wordpress-internal:
    driver: bridge
