apiVersion: v1
kind: ConfigMap
metadata:
  name: baserow-config
  namespace: book-stack
data:
  BASEROW_PUBLIC_URL: "http://localhost:92"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baserow-pvc
  namespace: book-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baserow
  namespace: book-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baserow
  template:
    metadata:
      labels:
        app: baserow
    spec:
      containers:
      - name: baserow
        image: baserow/baserow:1.33.4
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        env:
        - name: BASEROW_PUBLIC_URL
          valueFrom:
            configMapKeyRef:
              name: baserow-config
              key: BASEROW_PUBLIC_URL
        volumeMounts:
        - name: baserow-storage
          mountPath: /baserow/data
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
      volumes:
      - name: baserow-storage
        persistentVolumeClaim:
          claimName: baserow-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: baserow
  namespace: book-stack
spec:
  selector:
    app: baserow
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  type: ClusterIP