apiVersion: v1
kind: ConfigMap
metadata:
  name: nocodb-config
  namespace: book-stack
data:
  NC_DB: "mysql2://mysql.book-databases.svc.cluster.local:3306?u=root&p=rootpassword&d=defaultdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nocodb-pvc
  namespace: book-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocodb
  namespace: book-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nocodb
  template:
    metadata:
      labels:
        app: nocodb
    spec:
      containers:
      - name: nocodb
        image: nocodb/nocodb:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NC_DB
          valueFrom:
            configMapKeyRef:
              name: nocodb-config
              key: NC_DB
        volumeMounts:
        - name: nocodb-storage
          mountPath: /usr/app/data
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: nocodb-storage
        persistentVolumeClaim:
          claimName: nocodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nocodb
  namespace: book-stack
spec:
  selector:
    app: nocodb
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP