services:
  vikunja:
    image: vikunja/vikunja:latest
    restart: unless-stopped
    environment:
      VIKUNJA_DATABASE_HOST: postgres
      VIKUNJA_DATABASE_PASSWORD: ${VIKUNJA_DB_PASSWORD:-vikunja123}
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: ${VIKUNJA_DB_USER:-vikunja}
      VIKUNJA_DATABASE_DATABASE: ${VIKUNJA_DB_NAME:-vikunja}
      VIKUNJA_SERVICE_JWTSECRET: ${JWT_SECRET:-your-jwt-secret-here}
      VIKUNJA_SERVICE_FRONTENDURL: http://vikunja.localhost
    volumes:
      - vikunja_files:/app/vikunja/files
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vikunja.rule=Host(`vikunja.localhost`)"
      - "traefik.http.routers.vikunja.entrypoints=web"
      - "traefik.http.services.vikunja.loadbalancer.server.port=3456"
    networks:
      - shared-networks
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3456/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  vikunja_files:


networks:
  shared-networks:
    external: true
