services:
  openwebui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    restart: always
    volumes:
      - open-webui:/app/backend/data
    env_file:
      - ../.env
volumes:
  open-webui:
