services:
  traefik:
    container_name: nca_toolkit-container
    image: "traefik"
    restart: unless-stopped
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:85"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:449"
      # - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      # - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      # - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"

    ports:
      - "85:85"
      - "449:449"

    volumes:
      - traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  ncat:

    image: stephengpope/no-code-architects-toolkit:latest
    env_file:
      - .env

    ports:
      - "5699:8080"
      # labels:
      # - traefik.enable=true
      # - "traefik.http.routers.ncat.rule=Host(`APP_DOMAIN`)"
      # - traefik.http.routers.ncat.tls=true # optional; can remove if no TLS
      # - traefik.http.routers.ncat.entrypoints=websecure
      # Remove this line:
      # - traefik.http.routers.ncat.tls.certresolver=mytlschallenge

    volumes:
      - storage:/var/www/html/storage/app
      - logs:/var/www/html/storage/logs

    extra_hosts:
      - "host.docker.internal:172.17.0.1"

    restart: unless-stopped
    networks:
      - shared-net

volumes:
  traefik_data:
    driver: local
  storage:
    driver: local
  logs:
    driver: local

networks:
  shared-net:
    external: true
