services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    container_name: flaresolverr-container
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    # Remove direct port mapping - access through Traefik
    # ports:
    #   - "${PORT:-8191}:8191"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.localhost`)"
      - "traefik.http.routers.flaresolverr.entrypoints=web"
      - "traefik.http.services.flaresolverr.loadbalancer.server.port=8191"
    restart: unless-stopped
    networks:
      - shared-networks

networks:
  shared-networks:
    external: true
