services:
  couchdb:
    container_name: couchdb-container
    image: couchdb:3.3
    restart: unless-stopped
    ports:
      - "5984:5984"

    environment:

      COUCHDB_USER: ${COUCHDB_USER:-admin}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD:-admin123}
    volumes:
      - couchdb_data:/opt/couchdb/data
      - couchdb_config:/opt/couchdb/etc/local.d

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.couchdb.rule=Host(`couchdb.localhost`)"
      - "traefik.http.routers.couchdb.entrypoints=web"
      - "traefik.http.services.couchdb.loadbalancer.server.port=5984"

    networks:
      - shared-networks

    healthcheck:

      test: [ "CMD", "curl", "-f", "http://localhost:5984/_up" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  couchdb_data:
  couchdb_config:


networks:
  shared-networks:
    external: true
