services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    volumes:
      - ./phpmyadmin:/etc/phpmyadmin
    env_file:
      - ../.env
    restart: always
    ports:
      - 8081:80
    networks:
      - shared-networks

volumes:
  phpmyadmin:

networks:
  shared-networks:
    external: true
