services:
  redis:
    container_name: redis-container
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass redis123 --appendonly yes --appendfsync everysec
    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - shared-networks

    healthcheck:

      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:

      resources:

        limits:

          memory: 512M
        reservations:

          memory: 256M

volumes:
  redis_data:


networks:
  shared-networks:
    external: true
