services:
  backup:
    container_name: backup-container
    image: alpine
    command: sh -c "cd /volume && tar czf /backup/open-webui-backup.tar.gz ."
    volumes:
      - open-webui:/volume:ro
      - ./backup-data:/backup
    restart: "no"

volumes:
  open-webui:

# Added by centralization script
networks:
  shared-networks:
    external: true
  book-shared-network:
    external: true
  shared-net:
    external: true
