apiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: secure-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secure-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: secure-service-account
  namespace: default
roleRef:
  kind: Role
  name: secure-role
  apiGroup: rbac.authorization.k8s.io
