apiVersion: v1
kind: Pod
metadata:
  name: secure-pod-template
  labels:
    app: secure-app
  annotations:
    container.apparmor.security.beta.kubernetes.io/secure-container: runtime/default
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: secure-container
    image: nginx:alpine
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    ports:
    - containerPort: 8080
      protocol: TCP
    volumeMounts:
    - name: tmp-volume
      mountPath: /tmp
    - name: var-cache-volume
      mountPath: /var/cache/nginx
    - name: var-run-volume
      mountPath: /var/run
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
  volumes:
  - name: tmp-volume
    emptyDir: {}
  - name: var-cache-volume
    emptyDir: {}
  - name: var-run-volume
    emptyDir: {}
  restartPolicy: Always
