services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    restart: unless-stopped
    environment:
      - POCKETBASE_ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - POCKETBASE_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123456}
    volumes:
      - pocketbase_data:/pb_data
      - pocketbase_public:/pb_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pocketbase.rule=Host(`pocketbase.localhost`)"
      - "traefik.http.routers.pocketbase.entrypoints=web"
      - "traefik.http.services.pocketbase.loadbalancer.server.port=8080"
    networks:
      - shared-networks
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pocketbase_data:
  pocketbase_public:


networks:
  shared-networks:
    external: true
