services:
  vault:
    container_name: vault-container
    image: hashicorp/vault:latest
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/data
      - vault-logs:/vault/logs
      - ./config:/vault/config
    command: vault server -dev -dev-root-token-id="myroot" -dev-listen-address="0.0.0.0:8200"
    # Remove direct port mapping - access through Traefik
    ports:
      - "8200:8200"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.rule=Host(`vault.localhost`)"
      - "traefik.http.routers.vault.entrypoints=web"
      - "traefik.http.services.vault.loadbalancer.server.port=8200"
    networks:
      - shared-networks
    healthcheck:
      test: [ "CMD", "vault", "status" ]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  vault-data:
  vault-logs:


networks:
  shared-networks:
    external: true
