services:
  openwebui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    # Remove direct port mapping - access through Traefik
    # ports:
    #   - "3000:8080"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui.rule=Host(`openwebui.localhost`)"
      - "traefik.http.routers.openwebui.entrypoints=web"
      - "traefik.http.services.openwebui.loadbalancer.server.port=8080"
    volumes:
      - open-web-ui:/app/backend/data
    networks:
      - shared-networks
    env_file:
      - .env

volumes:
  open-web-ui:


networks:
  shared-networks:
    external: true
