services:
  cassandra:
    container_name: cassandra-container
    image: cassandra:4.1
    restart: unless-stopped
    ports:
      - "9042:9042"

    environment:

      CASSANDRA_CLUSTER_NAME: ${CASSANDRA_CLUSTER_NAME:-MyCluster}
      CASSANDRA_DC: ${CASSANDRA_DC:-datacenter1}
      CASSANDRA_RACK: ${CASSANDRA_RACK:-rack1}
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra

    labels:
      - "traefik.enable=false"

    networks:
      - shared-networks

    healthcheck:

      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 30s
      timeout: 10s
      retries: 10
    mem_limit: 2g

volumes:
  cassandra_data:


networks:
  shared-networks:
    external: true
