services:
  consul:
    container_name: consul-container
    image: consul:1.16
    restart: unless-stopped
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CLIENT_INTERFACE: eth0
    volumes:
      - consul_data:/consul/data
      - consul_config:/consul/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.consul.rule=Host(`consul.localhost`)"
      - "traefik.http.routers.consul.entrypoints=web"
      - "traefik.http.services.consul.loadbalancer.server.port=8500"
    networks:
      - shared-networks
    healthcheck:
      test: [ "CMD", "consul", "members" ]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  consul_data:
  consul_config:


networks:
  shared-networks:
    external: true
