services:
  nextcloud:
    container_name: nextcloud-container
    image: nextcloud:latest
    restart: always
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME:-nextcloud}
      - MYSQL_USER=${NEXTCLOUD_DB_USER:-nextcloud}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD:-nextcloud123}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-admin}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-admin123}
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.localhost

    volumes:
      - nextcloud_data:/var/www/html
      - nextcloud_apps:/var/www/html/custom_apps
      - nextcloud_config:/var/www/html/config

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.localhost`)"
      - "traefik.http.routers.nextcloud.entrypoints=web"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

    networks:
      - shared-networks

    healthcheck:

      test: [ "CMD", "curl", "-f", "http://localhost/status.php" ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s
    deploy:

      resources:

        limits:

          memory: 1G
        reservations:

          memory: 512M

volumes:
  nextcloud_data:
  nextcloud_apps:
  nextcloud_config:


networks:
  shared-networks:
    external: true
