services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_container
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - shared-networks

volumes:
  local_pgdata:


networks:
  shared-networks:
    external: true
