services:
  postgres:
    container_name: postgres-container
    build:

      context: .
      dockerfile: Dockerfile

    restart: always
    env_file:
      - .env

    ports:
      - "5432:5432"

    volumes:
      - local_pgdata:/var/lib/postgresql/data

    networks:
      - shared-networks

    healthcheck:

      test: [ "CMD-SHELL", "pg_isready -U postgres -h localhost -p 5432" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:

      resources:

        limits:

          memory: 1G
        reservations:

          memory: 512M

volumes:
  local_pgdata:


networks:
  shared-networks:
    external: true
